import type { Metadata } from "next";
import "./globals.css";
import AppContextProvider from "@/store/appContxt";
import {inter, manrope } from "@/constants/fonts";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Sound Check",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable}  ${manrope.variable}`}>
        <AppContextProvider>
          <Providers>
            {children}
          </Providers>
        </AppContextProvider>
      </body>
    </html>
  );
}
